wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1664261408.959441
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.6.13
      5: 0.13.1
      6: 4.18.0
      8:
      - 5
_wandb_kernel:
  desc: null
  value: nakama
apex:
  desc: null
  value: true
batch_scheduler:
  desc: null
  value: true
batch_size:
  desc: null
  value: 8
betas:
  desc: null
  value:
  - 0.9
  - 0.999
competition:
  desc: null
  value: FB3
debug:
  desc: null
  value: false
decoder_lr:
  desc: null
  value: 2.0e-05
encoder_lr:
  desc: null
  value: 2.0e-05
epochs:
  desc: null
  value: 4
eps:
  desc: null
  value: 1.0e-06
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: true
max_grad_norm:
  desc: null
  value: 1000
max_len:
  desc: null
  value: 512
min_lr:
  desc: null
  value: 1.0e-06
model:
  desc: null
  value: microsoft/deberta-v3-base
n_fold:
  desc: null
  value: 4
num_cycles:
  desc: null
  value: 0.5
num_warmup_steps:
  desc: null
  value: 0
num_workers:
  desc: null
  value: 4
print_freq:
  desc: null
  value: 20
scheduler:
  desc: null
  value: cosine
seed:
  desc: null
  value: 42
target_cols:
  desc: null
  value:
  - cohesion
  - syntax
  - vocabulary
  - phraseology
  - grammar
  - conventions
train:
  desc: null
  value: true
trn_fold:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
wandb:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.01
