dataset_class: second_stage_dataset
model_class: second_stage
architecture:
    pretrained_weights: ''
    prediction_mode: weighted_avg
    direct_result: true
    loss_weights: ''
dataset:
    fold: -1
    folds: 5
    label_columns: ['cohesion', 'syntax', 'vocabulary', 'phraseology', 'grammar', 'conventions']
    first_stage_outputs:
        - ./output/classification_v1/predicts.csv
        - ./output/regression_v1/predicts.csv
    with_probs:
        - true
        - false
environment:
    mixed_precision: false
    number_of_workers: 4
    seed: 42
experiment_name: two_stage_nn
training:
    add_types: false
    batch_size: 4
    differential_learning_rate: 4.0e-06
    differential_learning_rate_layers: []
    drop_last_batch: true
    epochs: 15
    grad_accumulation: 1
    gradient_clip: 5
    is_pseudo: false
    learning_rate: 8.0e-06
    loss_function: CrossEntropy
    optimizer: AdamW
    schedule: Linear
    use_awp: false
    warmup_epochs: 0.5
    weight_decay: 0.001
    gpu_limit:
        - {device: 0, fraction: 0.9}
    layer_wise_lr_decay:  -1
    early_stop_patience: 4
predicting:
    batch_size: 8
    return_probs: false
infering:
    infer_result_path: infer.csv
device: "cuda:0"


